base_url = "https://arbs09.de"
title = "@arbs09"
compile_sass = false
build_search_index = true
generate_feed = true
feed_filename = "rss.xml"
default_language = "en"

[markdown]
highlight_code = true
render_emoji = true


[extra]
author = "@arbs09"

