baseURL = 'https://arbs09.de/'
title = 'arbs09.de - photography blog'
theme = 'PaperMod'
enableRobotsTXT = true

[languages]
  [languages.en]
    languageName = "en"
    weight = 1

[minify]
  disableXML = true
  minifyOutput = true

[params]
    env = "production"
    defaultTheme = "auto"
    images = ["https://arbs09.de/blog/denmark-2023/images/dsc00040.jpg"]
    description = "the photography blog of arbs09."
    keywords = ["arbs09", "photography", "blog"]
    author = "arbs09"
    DateFormat = "January 2, 2006"
    comments = false
    ShowPostNavLinks = true
    hideSummary = false
    ShowWordCount = true
    ShowRssButtonInSectionTermList = true
    ShowBreadCrumbs = true
    ShowReadingTime = false
    disableScrollToTop = false
    ShowToc = true
    TocOpen = false
    ShowCodeCopyButtons = true

    [params.label]
      text = "arbs09.de"

    [params.social]
      twitter = 'Arbs09_'

    [params.homeInfoParams]
    Title = "@arbs09.de"
    Content = "Hey, I am arbs09, I post my photography stuff here. If you want you can visit my gallery with over 100 photos I took."

    [[params.socialIcons]]
    name = "email"
    url = "mailto:info@arbs09.de"

    [[params.socialIcons]]
    name = "github"
    url = "https://github.com/arbs09/"   

    [[params.socialIcons]]
    name = "key"
    url = "https://arbs09.dev/pgp.txt"

    [[params.socialIcons]]
    name = "mastodon"
    url = "https://mastodon.social/@arbs"

    [[params.socialIcons]]
    name = "instagram"
    url = "https://www.instagram.com/arbs09/"

    [[params.socialIcons]]
    name = "x"
    url = "https://x.com/Arbs09_"

[[menu.main]]
  identifier = "about"
  name = "about me"
  url = "/about/"
  weight = 10

[[menu.main]]
  identifier = "search"
  name = "search"
  url = "/search/"
  weight = 20

[[menu.main]]
  identifier = "archive"
  name = "archive"
  url = "/archive/"
  weight = 30

[[menu.main]]
  identifier = "gallery"
  name = "my gallery"
  url = "https://gallery.arbs09.de"
  weight = 40

[[menu.main]]
  identifier = "devblog"
  name = "my dev blog"
  url = "https://arbs09.dev"
  weight = 50

[outputs]
  home = ["HTML", "RSS", "JSON"]
