baseURL = 'https://arbs09.de/'
languageCode = 'en'
title = 'arbs09.de'
theme = 'PaperMod'
enableRobotsTXT = true
defaultContentLanguage = "en"

[languages]
  [languages.en]
    languageName = "en"
    weight = 1

[minify]
  disableXML = true
  minifyOutput = true

[params]
    env = "production"
    defaultTheme = "auto"
    DateFormat = "January 2, 2006"
    comments = false
    ShowPostNavLinks = true
    hideSummary = false
    ShowWordCount = true
    ShowRssButtonInSectionTermList = true
    ShowBreadCrumbs = true
    ShowReadingTime = false
    disableScrollToTop = false
    ShowToc = true
    TocOpen = false
    ShowCodeCopyButtons = true

    [params.homeInfoParams]
    Title = "arbs09"
    Content = "Hey, I am @arbs09 and you are on my photography page / site."

    [[params.socialIcons]]
    name = "email"
    url = "mailto:info@arbs09.de"

    [[params.socialIcons]]
    name = "github"
    url = "https://github.com/arbs09/"   

    [[params.socialIcons]]
    name = "key"
    url = "https://arbs09.dev/pgp.txt"

    [[params.socialIcons]]
    name = "mastodon"
    url = "https://mastodon.social/@arbs"

    [[params.socialIcons]]
    name = "instagram"
    url = "https://www.instagram.com/arbs09/"

    [[params.socialIcons]]
    name = "x"
    url = "https://x.com/Arbs09_"

[[menu.main]]
  identifier = "about"
  name = "about"
  url = "/about/"
  weight = 10

[[menu.main]]
  identifier = "search"
  name = "search"
  url = "/search/"
  weight = 20

[[menu.main]]
  identifier = "archive"
  name = "archive"
  url = "/archive/"
  weight = 30

[[menu.main]]
  identifier = "gallery"
  name = "my gallery"
  url = "https://gallery.arbs09.de"
  weight = 40

[outputs]
  home = ["HTML", "RSS", "JSON"]

