name: CI
run-name: Hugo blog deployment
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: deploy
    steps:
      - name: Checkout the current branch
        uses: actions/checkout@v3

      - name: Initialize the ssh-agent
        uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Install Hugo
        run: sudo apt install hugo
        
      - name: Install Dart Sass
        run: sudo snap install dart-sass

      - name: Build the website
        run: hugo

      - name: Replace the server address in knonw hosts
        run: >-
          sed "s/changeme/$DEPLOY_SERVER/g" -i known_hosts
        env:
          DEPLOY_SERVER: ${{ secrets.DEPLOY_SERVER }}

      - name: Scan the host key
        run: mkdir -p ~/.ssh/ && cp known_hosts ~/.ssh/known_hosts

      - name: Deploy the website
        run: >-
          rsync -avx -e 'ssh' --delete --exclude '.ssh' public/ $DEPLOY_USERNAME@$DEPLOY_SERVER:./
        env:
          DEPLOY_SERVER: ${{ secrets.DEPLOY_SERVER }}
          DEPLOY_USERNAME: ${{ secrets.DEPLOY_USERNAME }}